# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ConnectionBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ConnectionBox.setGeometry(QtCore.QRect(50, 40, 181, 121))
        self.ConnectionBox.setObjectName("ConnectionBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.ConnectionBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 161, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ConnectionLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ConnectionLayout.setContentsMargins(0, 0, 0, 0)
        self.ConnectionLayout.setObjectName("ConnectionLayout")
        self.PortLayout = QtWidgets.QHBoxLayout()
        self.PortLayout.setObjectName("PortLayout")
        self.PortLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.PortLabel.setObjectName("PortLabel")
        self.PortLayout.addWidget(self.PortLabel)
        self.PortField = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.PortField.setObjectName("PortField")
        self.PortLayout.addWidget(self.PortField)
        self.ConnectionLayout.addLayout(self.PortLayout)
        self.ConnectionLaserButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ConnectionLaserButton.setObjectName("ConnectionLaserButton")
        self.ConnectionLayout.addWidget(self.ConnectionLaserButton)
        self.ConnectionStagesButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ConnectionStagesButton.setObjectName("ConnectionStagesButton")
        self.ConnectionLayout.addWidget(self.ConnectionStagesButton)
        self.LaserControlBox = QtWidgets.QGroupBox(self.centralwidget)
        self.LaserControlBox.setGeometry(QtCore.QRect(270, 210, 331, 171))
        self.LaserControlBox.setFlat(False)
        self.LaserControlBox.setCheckable(False)
        self.LaserControlBox.setObjectName("LaserControlBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.LaserControlBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 19, 276, 141))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.LaserControlLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.LaserControlLayout.setContentsMargins(0, 0, 0, 0)
        self.LaserControlLayout.setObjectName("LaserControlLayout")
        self.StartStopButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.StartStopButton.setObjectName("StartStopButton")
        self.LaserControlLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.StartStopButton)
        self.FileBox = QtWidgets.QPushButton(self.formLayoutWidget)
        self.FileBox.setObjectName("FileBox")
        self.LaserControlLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.FileBox)
        self.StretchButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.StretchButton.setObjectName("StretchButton")
        self.LaserControlLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.StretchButton)
        self.NumberOfCyclesLayout = QtWidgets.QHBoxLayout()
        self.NumberOfCyclesLayout.setObjectName("NumberOfCyclesLayout")
        self.NumberOfCyclesLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.NumberOfCyclesLabel.setObjectName("NumberOfCyclesLabel")
        self.NumberOfCyclesLayout.addWidget(self.NumberOfCyclesLabel)
        self.NumberOfCyclesField = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.NumberOfCyclesField.setObjectName("NumberOfCyclesField")
        self.NumberOfCyclesLayout.addWidget(self.NumberOfCyclesField)
        self.LaserControlLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.NumberOfCyclesLayout)
        self.NumberOfCycleLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.NumberOfCycleLabel.setObjectName("NumberOfCycleLabel")
        self.LaserControlLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.NumberOfCycleLabel)
        self.NumberOfCycleField = QtWidgets.QLabel(self.formLayoutWidget)
        self.NumberOfCycleField.setText("")
        self.NumberOfCycleField.setObjectName("NumberOfCycleField")
        self.LaserControlLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.NumberOfCycleField)
        self.SetToTenButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.SetToTenButton.setObjectName("SetToTenButton")
        self.LaserControlLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.SetToTenButton)
        self.MoveOutButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.MoveOutButton.setObjectName("MoveOutButton")
        self.LaserControlLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.MoveOutButton)
        self.StagesConrtolBox = QtWidgets.QGroupBox(self.centralwidget)
        self.StagesConrtolBox.setGeometry(QtCore.QRect(50, 210, 171, 171))
        self.StagesConrtolBox.setObjectName("StagesConrtolBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.StagesConrtolBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 151, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.StagesLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.StagesLayout.setContentsMargins(0, 0, 0, 0)
        self.StagesLayout.setObjectName("StagesLayout")
        self.StagesToZerosButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.StagesToZerosButton.setObjectName("StagesToZerosButton")
        self.StagesLayout.addWidget(self.StagesToZerosButton, 0, 0, 1, 2)
        self.StagesToHomeButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.StagesToHomeButton.setObjectName("StagesToHomeButton")
        self.StagesLayout.addWidget(self.StagesToHomeButton, 1, 0, 1, 2)
        self.MoveStagesField = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.MoveStagesField.setObjectName("MoveStagesField")
        self.StagesLayout.addWidget(self.MoveStagesField, 2, 1, 1, 1)
        self.MoveStagesButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.MoveStagesButton.setObjectName("MoveStagesButton")
        self.StagesLayout.addWidget(self.MoveStagesButton, 2, 0, 1, 1)
        self.LogBox = QtWidgets.QGroupBox(self.centralwidget)
        self.LogBox.setGeometry(QtCore.QRect(280, 50, 331, 101))
        self.LogBox.setObjectName("LogBox")
        self.LogField = QtWidgets.QTextBrowser(self.LogBox)
        self.LogField.setGeometry(QtCore.QRect(10, 20, 311, 71))
        self.LogField.setObjectName("LogField")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Taper Making UI v.0.6_Dasha"))
        self.ConnectionBox.setTitle(_translate("MainWindow", "Connection"))
        self.PortLabel.setText(_translate("MainWindow", "Laser port: COM"))
        self.PortField.setText(_translate("MainWindow", "1"))
        self.ConnectionLaserButton.setText(_translate("MainWindow", "Laser"))
        self.ConnectionStagesButton.setText(_translate("MainWindow", "Stages"))
        self.LaserControlBox.setTitle(_translate("MainWindow", "Laser controlling"))
        self.StartStopButton.setText(_translate("MainWindow", "Start/stop"))
        self.FileBox.setText(_translate("MainWindow", "Please select file"))
        self.StretchButton.setText(_translate("MainWindow", "Stretch"))
        self.NumberOfCyclesLabel.setText(_translate("MainWindow", "Total number of cycles:"))
        self.NumberOfCyclesField.setText(_translate("MainWindow", "19"))
        self.NumberOfCycleLabel.setText(_translate("MainWindow", "Number of cylce:"))
        self.SetToTenButton.setText(_translate("MainWindow", "Set to 10%"))
        self.MoveOutButton.setText(_translate("MainWindow", "Move out"))
        self.StagesConrtolBox.setTitle(_translate("MainWindow", "Stages conrtrolling"))
        self.StagesToZerosButton.setText(_translate("MainWindow", "Stages to zeros"))
        self.StagesToHomeButton.setText(_translate("MainWindow", "Stages to home"))
        self.MoveStagesButton.setText(_translate("MainWindow", "Move stages"))
        self.LogBox.setTitle(_translate("MainWindow", "Log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

